services:
  - type: web
    name: ctf-django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ctf.wsgi --log-file -
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ctf.settings
      - key: SECRET_KEY
        value: your-django-secret-key
      - key: ALLOWED_HOSTS
        value: ctf-django-app.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: ctf-db
          property: connectionString

databases:
  - name: ctf-db
    databaseName: ctf_db
    user: ctf_user
